version: "3"
services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks: 
      - poll-tier
    links: 
      - redis
    depends_on:
      - redis
    restart: always
  redis:
    image: redis:alpine
    hostname: redis
    volumes:
    - ./config/redis.conf:/redis.conf
    ports:
      - "6379:6379"
    networks: 
      - poll-tier
      - back-tier
    command: [ "redis-server", "/redis.conf" ]
    restart: always
  worker:
    build: ./worker
    command: java -jar worker-jar-with-dependencies.jar
    links:
      - redis
    depends_on:
      - redis
    networks: 
      - back-tier
    restart: always
  db:
    image: postgres:11
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    networks: 
      - result-tier
      - back-tier
    restart: always
  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
    restart: always
volumes:
    db-data:
networks:
  poll-tier: 
  result-tier:  
  back-tier: